### ISSUE TITLE
Markup issues on Bubble chart

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/ng2-tools-page#51]
![selection_113](https://user-images.githubusercontent.com/18219232/31169067-273d36dc-a900-11e7-87fc-9defeaf3ae3d.png)

**Comment by angieskazka** [comment]
@Sergey Khristenko @vyacheslav.chub
you sometimes can see the broken styling on tools page when developing locally
https://github.com/Gapminder/ng2-tools-page/issues/51

@dab suspects that the reason is the different cache for localhost:4200/ and localhost:4200/tools/, and an automatic redirect from the first to the second will help

**Comment by angieskazka** [comment]
@sergeyKhristenko @buchslava haven't seen this in a while. have you?
