### ISSUE TITLE
'Back' button in browser doesn't restore previous state

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/ng2-tools-page#54]
The url is changing, but the page doesn't.

**Comment by buchslava** [comment]
This case is more complex: if url is not changing then is normal, because we are using ngrx; but next case is wrong:

1. open bubble charts
2. select a couple of countries
3. click back -> ok, the chart was reverted
4. click again -> not ok chart was reverted

expected behavior: chert state should be reverted after second `back click`

**Comment by buchslava** [comment]
Seems Vizabi issue when current state is NOT empty but next state is empty. It looks like `Object.assign` issue...
