### ISSUE TITLE
how to improvement

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ng2-tools-page#85]
add how to iframe when it expected -> before how to modal opening

**Comment by angieskazka** [comment]
@buchslava it didn't appear at all for me
we should: 
have a video actually showing up after we click "how to use" :)
have a container of the final size even before the video comes in, so that nothing would jump visibly

![image](https://user-images.githubusercontent.com/3648190/31691100-1e32afaa-b395-11e7-997b-93b852356a30.png)
